//@version=6
indicator(title="Moving Average Weighted", shorttitle="WMA", overlay=true, timeframe="", timeframe_gaps=true)

len = input.int(defval = 12, minval=1, title="Length") // default 12, min 1, title Length
src = input(close, title="Source") // source list: close, open, high, low, hl2 (default close)
offset = input.int(title="Offset", defval=0, minval=-500, maxval=500, display = display.data_window) // default 0, min -500, max 500, display in data window
price = input.price(defval = 60.00) // default 60.00, price input type

out = ta.wma(src, len)
plot(out, title="WMA", color=color.blue, offset=offset)