// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © fethicekinmez

//@version=6
string isim = "Test Komut dosyam"
indicator(isim, overlay = true)

float f = 6.5
int i = 90
bool b = true
string s = "Fethi Çekinmez'in indikatörü" + str.tostring(i)

// Using the variables in labels
label.new(bar_index, 70.0, s, color = color.red, size = size.large)



plot(close)
