// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © fethicekinmez

//@version=6
indicator("Komut dosyam", overlay = true)

int userInput = input.int(defval = 0, title = "Bir Sayı Gir", minval=0, maxval=100)
string txt = "Girilen Sayı: " + str.tostring(userInput)

label.new(bar_index, 68, text = txt, textcolor = color.white, size = 13)
plot(close, color =  userInput >= 10 ? color.red : color.blue)
